# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[ ➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[ ➜](bold red)"
vicmd_symbol = "[ ➜](bold green)"

[directory]
disabled = false
truncation_symbol = ".../"

[git_status]
disabled = false

[hostname]
disabled = false
ssh_only = false
format = "[@$hostname](white bold) in "

[line_break]
disabled = false

[package]
disabled = true

[python]
python_binary = ["python3", "python"]

[shell]
fish_indicator = "f"
zsh_indicator = "z"
bash_indicator = "b"
disabled = false

[status]
disabled = false

[username]
show_always = true
format = "[$user](white bold)"
